

# This file was *autogenerated* from the file dimscript.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 = Integer(21888242871839275222246405745257275088696311157297823662689037894645226208583); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8)
F = GF(
    _sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 
)


def build_M_old(k, s, base_field=F):
    if k <= _sage_const_0  or s <= _sage_const_0 :
        raise ValueError("k and s must be positive integers")

    base_vars = ["t", "a", "c", "x"]
    l_vars = [f"L_{i}_{j}" for i in range(k) for j in range(_sage_const_4 )]
    r_vars = [f"R_{i}_{j}" for i in range(_sage_const_4 ) for j in range(k)]
    names = base_vars + l_vars + r_vars

    R0 = PolynomialRing(base_field, names=names)
    P = R0.fraction_field()
    gens = P.gens_dict()

    t = gens["t"]
    a = gens["a"]
    c = gens["c"]
    b = c**_sage_const_2  / a      #to enforce ab = c^2
    x = gens["x"]

    L = Matrix(P, k, _sage_const_4 , [gens[f"L_{i}_{j}"] for i in range(k) for j in range(_sage_const_4 )])
    R = Matrix(P, _sage_const_4 , k, [gens[f"R_{i}_{j}"] for i in range(_sage_const_4 ) for j in range(k)])

    U = Matrix(P, 
        [[a, c, -x, P(_sage_const_0 )],
         [c, b, P(_sage_const_0 ), x ],
         [P(_sage_const_0 ), P(_sage_const_0 ), b, c],
         [P(_sage_const_0 ), P(_sage_const_0 ), c, a]])

    # Coefficient arrays now have length 2*s - 1.
    gamma = [t**m for m in range(_sage_const_2  * s - _sage_const_1 )]
 
    Gamma = Matrix(P, s, s, lambda i, j: gamma[i + j])
    
    G = L * U * R

    M = G.tensor_product(Gamma)
    M_flat = Matrix(
        P,
        k * k,
        _sage_const_2  * s - _sage_const_1 ,
        lambda row, ell: G[row // k, row % k] * gamma[ell],
    )
    M_flat_polys = [M_flat[i, j] for i in range(M_flat.nrows()) for j in range(M_flat.ncols())]
    vars = P.gens()
    jacobian_flat = Matrix(
        P,
        len(M_flat_polys),
        len(vars),
        lambda i, j: M_flat_polys[i].derivative(vars[j]),
    )

    return {
        "ring": P,
        "M": M,
        "M_flat": M_flat,
        "M_flat_polys": M_flat_polys,
        "jacobian_flat": jacobian_flat,
        "vars": vars,
        "G": G,
        "Gamma": Gamma,
        "gamma": gamma,
        "L": L,
        "R": R,
    }


def build_M_new(k, s, base_field=F, with_scale=False):
    if k <= _sage_const_0  or s <= _sage_const_0 :
        raise ValueError("k and s must be positive integers")

    base_vars = ["t", "u", "a", "c", "x"]
    l_vars = [f"L_{i}_{j}" for i in range(k) for j in range(_sage_const_2 )]
    r_vars = [f"R_{i}_{j}" for i in range(_sage_const_2 ) for j in range(k)]
    names = base_vars + l_vars + r_vars

    R0 = PolynomialRing(base_field, names=names)
    P = R0.fraction_field()
    gens = P.gens_dict()

    t = gens["t"]
    u = gens["u"]
    a = gens["a"]
    c = gens["c"]
    b = c**_sage_const_2  / a     # to enforce ab = c^2
    x = gens["x"]

    L = Matrix(P, k, _sage_const_2 , [gens[f"L_{i}_{j}"] for i in range(k) for j in range(_sage_const_2 )])
    R = Matrix(P, _sage_const_2 , k, [gens[f"R_{i}_{j}"] for i in range(_sage_const_2 ) for j in range(k)])

    U0 = Matrix(P, [[a, c], [c, b]])
    U1 = Matrix(P, [[P(_sage_const_0 ), -x], [x, P(_sage_const_0 )]])

    # Coefficient arrays now have length 2*s - 1.
    gamma0 = [t**m for m in range(_sage_const_2  * s - _sage_const_1 )]
    gamma1 = [P(_sage_const_0 )] + [m * t**(m - _sage_const_1 ) for m in range(_sage_const_1 , _sage_const_2  * s - _sage_const_1 )]
    if with_scale:
        gamma1 = [gamma1[i] + u * gamma0[i] for i in range(_sage_const_0 , _sage_const_2  * s - _sage_const_1 )]

    Gamma0 = Matrix(P, s, s, lambda i, j: gamma0[i + j])
    Gamma1 = Matrix(P, s, s, lambda i, j: gamma1[i + j])

    G0 = L * U0 * R
    G1 = L * U1 * R

    M = G0.tensor_product(Gamma1) + G1.tensor_product(Gamma0)
    M_flat = Matrix(
        P,
        k * k,
        _sage_const_2  * s - _sage_const_1 ,
        lambda row, ell: G0[row // k, row % k] * gamma1[ell]
        + G1[row // k, row % k] * gamma0[ell],
    )
    M_flat_polys = [M_flat[i, j] for i in range(M_flat.nrows()) for j in range(M_flat.ncols())]
    vars = P.gens()
    jacobian_flat = Matrix(
        P,
        len(M_flat_polys),
        len(vars),
        lambda i, j: M_flat_polys[i].derivative(vars[j]),
    )

    return {
        "ring": P,
        "M": M,
        "M_flat": M_flat,
        "M_flat_polys": M_flat_polys,
        "jacobian_flat": jacobian_flat,
        "vars": vars,
        "G0": G0,
        "G1": G1,
        "Gamma0": Gamma0,
        "Gamma1": Gamma1,
        "gamma0": gamma0,
        "gamma1": gamma1,
        "L": L,
        "R": R,
    }

def build_M_antisym(k, s, base_field=F):
    if k <= _sage_const_0  or s <= _sage_const_0 :
        raise ValueError("k and s must be positive integers")

    base_vars = ["t", "a", "b", "c", "x"]
    l_vars = [f"L_{i}_{j}" for i in range(k) for j in range(_sage_const_4 )]
    names = base_vars + l_vars

    R0 = PolynomialRing(base_field, names=names)
    P = R0.fraction_field()
    gens = P.gens_dict()

    t = gens["t"]
    a = gens["a"]
    c = gens["c"]
    b = gens["b"]      
    d = a*b/c         #to enforce ab = cd
    x = gens["x"]

    L = Matrix(P, k, _sage_const_4 , [gens[f"L_{i}_{j}"] for i in range(k) for j in range(_sage_const_4 )])
    R = Matrix(P, _sage_const_4 , k, [gens[f"L_{j}_{i}"] for i in range(_sage_const_4 ) for j in range(k)])
    # transposed matrix to preserve antisymmetry

    o = P(_sage_const_0 ) #zero
    U = Matrix(P, 
        [[o, -x, a, c],
         [x, o, d, b ],
         [-a, -d, o, o],
         [-c, -b, o, o]])

    # Coefficient arrays now have length 2*s - 1.
    gamma = [t**m for m in range(_sage_const_2  * s - _sage_const_1 )]
 
    Gamma = Matrix(P, s, s, lambda i, j: gamma[i + j])
    
    G = L * U * R

    M = G.tensor_product(Gamma)
    M_flat = Matrix(
        P,
        k * k,
        _sage_const_2  * s - _sage_const_1 ,
        lambda row, ell: G[row // k, row % k] * gamma[ell],
    )
    M_flat_polys = [M_flat[i, j] for i in range(M_flat.nrows()) for j in range(M_flat.ncols())]
    vars = P.gens()
    jacobian_flat = Matrix(
        P,
        len(M_flat_polys),
        len(vars),
        lambda i, j: M_flat_polys[i].derivative(vars[j]),
    )

    return {
        "ring": P,
        "M": M,
        "M_flat": M_flat,
        "M_flat_polys": M_flat_polys,
        "jacobian_flat": jacobian_flat,
        "vars": vars,
        "G": G,
        "Gamma": Gamma,
        "gamma": gamma,
        "L": L,
        "R": R,
    }


s = _sage_const_3 

for k in range(_sage_const_4 , _sage_const_7 ):
    d = build_M_antisym(k, s, base_field=F)
    P = d["ring"]
    g = P.gens_dict()
    M = d["M"]
    J = d["jacobian_flat"]
    sample = {var: F.random_element() for var in P.gens()}
    dim_OT = J.subs(sample).rank()
    assert(dim_OT == _sage_const_2 *k - _sage_const_2 )
    print("antisym embedding, k = {}, s = {}, dim_OT = {}".format(k, s, dim_OT))

## code above confirms that what we obtain has generic form antisymmetric of rk 2 \otimes toeplitz of rank 1
## now let's avoid divisions and just add up m terms of this form to check when they generate everything

def build_sum(k, s, m, base_field=F):
    if k <= _sage_const_0  or s <= _sage_const_0  or m <= _sage_const_0 :
        raise ValueError("k, s and m must be positive integers")

    t_vars = [f"t_{r}" for r in range(m)]
    a_vars = [f"a_{r}_{i}" for r in range(m) for i in range(k)]
    b_vars = [f"b_{r}_{i}" for r in range(m) for i in range(k)]
    names = t_vars + a_vars + b_vars

    P = PolynomialRing(base_field, names=names)
    gens = P.gens_dict()

    G_terms = []
    gamma_terms = []
    Gamma_terms = []

    for r in range(m):
        a = vector(P, [gens[f"a_{r}_{i}"] for i in range(k)])
        b = vector(P, [gens[f"b_{r}_{i}"] for i in range(k)])

        # a \wedge b = a^t b - b^t a (antisymmetric, rank <= 2)
        G = a.column() * b.row() - b.column() * a.row()
        gamma = [gens[f"t_{r}"] ** ell for ell in range(_sage_const_2  * s - _sage_const_1 )]
        Gamma = Matrix(P, s, s, lambda i, j: gamma[i + j])

        G_terms.append(G)
        gamma_terms.append(gamma)
        Gamma_terms.append(Gamma)

    M = sum(G_terms[r].tensor_product(Gamma_terms[r]) for r in range(m))
    M_flat = Matrix(
        P,
        k * k,
        _sage_const_2  * s - _sage_const_1 ,
        lambda row, ell: sum(
            G_terms[r][row // k, row % k] * gamma_terms[r][ell] for r in range(m)
        ),
    )

    M_flat_polys = [M_flat[i, j] for i in range(M_flat.nrows()) for j in range(M_flat.ncols())]
    vars = P.gens()
    jacobian_flat = Matrix(
        P,
        len(M_flat_polys),
        len(vars),
        lambda i, j: M_flat_polys[i].derivative(vars[j]),
    )

    return {
        "ring": P,
        "M": M,
        "M_flat": M_flat,
        "M_flat_polys": M_flat_polys,
        "jacobian_flat": jacobian_flat,
        "vars": vars,
        "G_terms": G_terms,
        "Gamma_terms": Gamma_terms,
        "gamma_terms": gamma_terms,
    }

s = _sage_const_3 
k = _sage_const_4 

for m in range(_sage_const_1 , _sage_const_8 ):
    d = build_sum(k, s, m, base_field=F)
    P = d["ring"]
    g = P.gens_dict()
    M = d["M"]
    J = d["jacobian_flat"]
    sample = {var: F.random_element() for var in P.gens()}
    dim_2m_rk = J.subs(sample).rank()
    print("k = {}, s = {}, m = {}, rank 2: {}".format(k, s, m, dim_2m_rk))

